# Generated by Django 3.2.9 on 2021-12-11 06:22

import Register_Page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Nick_Name',
            field=models.CharField(default='Hey', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Profile_pic',
            field=Register_Page.models.CloudinaryField(default='', max_length=255, verbose_name='Profile_Pic'),
        ),
    ]
