# Generated by Django 3.2.9 on 2021-12-19 18:23

import Register_Page.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Page', '0002_auto_20211211_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_pic',
            field=Register_Page.models.CloudinaryField(max_length=255, verbose_name='Profile_Pic'),
        ),
    ]
