# Generated by Django 3.2.9 on 2022-03-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Page', '0004_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='Name',
            field=models.CharField(default='Cool Theme?', max_length=100),
        ),
    ]
