# Generated by Django 3.2.9 on 2022-03-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Page', '0005_theme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='Body_Back',
            field=models.CharField(default='#2d2424', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Card_Back',
            field=models.CharField(default='#2d2424', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Card_Border',
            field=models.CharField(default='#020440', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Card_Color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Nav_Back',
            field=models.CharField(default='#020440', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Nav_Color',
            field=models.CharField(default='#d8c70e', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='Nav_Line',
            field=models.CharField(default='#d8c70e', max_length=10),
        ),
    ]
