# Generated by Django 3.2.9 on 2022-05-15 13:43

import Post.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(default='None', max_length=50)),
                ('Logo', models.CharField(default='None', max_length=150)),
                ('NavBack', models.CharField(default='None', max_length=50)),
                ('NavColor', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Post', Post.models.CloudinaryField(max_length=255, verbose_name='Post')),
                ('Type', models.CharField(default='Img', max_length=50)),
                ('Points', models.IntegerField(default=0)),
                ('Pinned', models.CharField(default=0, max_length=1)),
                ('Daily', models.CharField(default=0, max_length=1)),
                ('Day', models.CharField(default='None', max_length=50)),
                ('Date', models.CharField(default='None', max_length=50)),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('voted', models.CharField(default='0', max_length=1)),
                ('meme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.meme')),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seen', models.CharField(default='0', max_length=1)),
                ('Meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.meme')),
                ('Op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Define', models.CharField(max_length=200)),
                ('Defend', models.CharField(default='Aye', max_length=100)),
                ('Attack', models.CharField(default='Nay', max_length=100)),
                ('Creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Post', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Post.meme')),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('cnt', models.TextField(default='Sorry an Error is here', max_length=500)),
                ('side', models.CharField(default='0', max_length=1)),
                ('Edited', models.CharField(default='0', max_length=1)),
                ('Edit_Time', models.DateTimeField(auto_now_add=True)),
                ('Edit_1', models.TextField(default='', max_length=500)),
                ('Edit_2', models.TextField(default='', max_length=500)),
                ('Reply', models.CharField(default='0', max_length=1)),
                ('Replied_Msg', models.CharField(default='69', max_length=10)),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ring', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.ring')),
            ],
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('voted', models.CharField(default='0', max_length=1)),
                ('meme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.meme')),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('reply', models.CharField(default='0', max_length=1)),
                ('cmnt_chn', models.CharField(default='1', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('not_post_method_ok', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.meme')),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
