# Generated by Django 3.2.9 on 2022-05-27 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20220527_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downvote',
            name='created',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='created',
        ),
        migrations.AlterField(
            model_name='msg',
            name='Edit_Time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 11, 18, 3, 890019)),
        ),
    ]
