# Generated by Django 3.2.9 on 2022-05-30 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20220527_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='Edit_Time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 15, 3, 4, 271403)),
        ),
        migrations.AlterField(
            model_name='msg',
            name='Reply',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
