# Generated by Django 3.2.9 on 2022-06-09 07:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0005_auto_20220530_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Downvote',
            new_name='Vote',
        ),
        migrations.AlterField(
            model_name='msg',
            name='Edit_Time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 12, 52, 16, 620248)),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
