# Generated by Django 3.2.9 on 2022-06-11 07:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0006_auto_20220609_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Points',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='msg',
            name='Edit_Time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 13, 21, 39, 48168)),
        ),
        migrations.CreateModel(
            name='Cmnt_Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.CharField(default='0', max_length=1)),
                ('Cmnt', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.comment')),
                ('op', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
