# Generated by Django 3.2.9 on 2022-06-19 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20220611_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='Edit_Time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 15, 55, 21, 128062)),
        ),
    ]
