# Generated by Django 3.2.9 on 2022-06-19 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_alter_msg_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='meme',
            name='Points',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='msg',
            name='Edit_Time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 23, 22, 23, 778748)),
        ),
    ]
